In [1]:
import numpy as np

In [2]:
arr1 = np.arange(9).reshape(3, 3)

In [3]:
arr1.shape

(3, 3)

In [4]:
np.ones((3, 5), dtype= np.int64)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int64)

In [5]:
rand_arr = np.random.randint(1, 100, (4, 5) )

In [6]:
rand_arr.sum()

1143

In [7]:
rand_arr.min()

4

In [8]:
rand_arr.max()

92

In [9]:
arr3 = np.random.random( (4, 5) )*100

In [10]:
rand_arr*10

array([[480, 180, 850, 540, 870],
       [820, 700, 110, 570, 900],
       [730, 900,  40, 130, 320],
       [920, 380, 540, 920, 530]])

In [11]:
arr1 = np.arange(11, 20).reshape(3, 3)

In [12]:
arr1[1]

array([14, 15, 16])

In [13]:
arr1

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [14]:
arr1[1, 2]

16

In [15]:
arr2 = np.arange(1, 21).reshape(4, 5)

In [16]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [17]:
arr2[3, 3]

19

In [18]:
arr2[ 2, 3:5 ]

array([14, 15])

In [19]:
arr2[1:4, 1]

array([ 7, 12, 17])

In [20]:
[1, 7, 13, 19]

[1, 7, 13, 19]

In [21]:
arr2.diagonal()

array([ 1,  7, 13, 19])

In [22]:
np.floor(arr3)

array([[22., 11., 51., 98.,  9.],
       [26., 47., 48., 73., 44.],
       [29., 55., 79., 38., 13.],
       [ 9., 32., 19., 78., 90.]])

In [23]:
np.ceil(arr3)

array([[23., 12., 52., 99., 10.],
       [27., 48., 49., 74., 45.],
       [30., 56., 80., 39., 14.],
       [10., 33., 20., 79., 91.]])

In [24]:
arr3

array([[22.7944955 , 11.80292027, 51.31148261, 98.29458342,  9.40694098],
       [26.89282241, 47.81358246, 48.86172775, 73.24102443, 44.85897286],
       [29.89052141, 55.37420452, 79.72993581, 38.42920715, 13.15495349],
       [ 9.74073081, 32.45464412, 19.8705765 , 78.84356427, 90.87758344]])

In [25]:
# Stacking Vertically - no. of columns should be same
arr4 = np.arange(1, 7).reshape(2, 3)
arr5 = np.arange(8, 14).reshape(2, 3)

In [26]:
arr4

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
arr5

array([[ 8,  9, 10],
       [11, 12, 13]])

In [28]:
np.vstack((arr4, arr5))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [11, 12, 13]])

In [29]:
np.hsplit(arr4, 3)

[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]])]

In [30]:
arr4.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [31]:
arr4.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [32]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
arr4*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [34]:
arr4 * arr5

array([[ 8, 18, 30],
       [44, 60, 78]])

In [35]:
arr2 * arr4

ValueError: operands could not be broadcast together with shapes (4,5) (2,3) 

In [ ]:
arr4 @ arr5

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [ ]:
arr4

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr4

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr6 = np.arange(1, 5).reshape(2, 2)

In [ ]:
arr6

array([[1, 2],
       [3, 4]])

In [ ]:
[2, 2] [2, 3] 

In [ ]:
arr6 @ arr4

array([[ 9, 12, 15],
       [19, 26, 33]])

In [ ]:
arr6.dot(arr4)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [ ]:
bool_array = arr2 % 2 == 0

In [ ]:
arr2[bool_array]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
arr2[ arr2 == 2 ]

array([2])

In [ ]:
arr2[ arr2 % 2 == 0 ]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
arr2.trace()

40